<script>
    var grid_lang = {
        percentsymbol: "%",
        currencysymbol: "$",
        currencysymbolposition: "before",
        decimalseparator: '.',
        thousandsseparator: ',',
        pagergotopagestring: "Đi tới trang:",
        pagershowrowsstring: "Xem các hàng:",
        pagerrangestring: " của ",
        pagerpreviousbuttonstring: "trước",
        pagernextbuttonstring: "sau",
        groupsheaderstring: "Kéo một cột và thả nó vào đây để nhóm theo cột đó",
        sortascendingstring: "Sắp xếp tăng dần",
        sortdescendingstring: "Sắp xếp giảm dần",
        sortremovestring: "Xóa sắp xếp",
        groupbystring: "Nhóm bởi cột này",
        groupremovestring: "Xóa bỏ nhóm",
        filterclearstring: "Làm sạch",
        filterstring: "Lọc",
        filtershowrowstring: "Xem các hàng từ:",
        filtershowrowdatestring: "Xem các hàng từ ngày:",
        filterorconditionstring: "Hoặc",
        filterandconditionstring: "Và",
        filterselectallstring: "(Chọn tất cả)",
        filterchoosestring: "Làm ơn chọn:",
        filterstringcomparisonoperators: ['trống', 'không trống', 'có chứa', 'có chứa(phù hợp hoa thường)',
            'không chứa', 'không chứa (phù hợp hoa thường)', 'bắt đầu với', 'bất đầu với(phù hợp hoa thường)',
            'kết thúc với', 'kết thúc với(phù hợp hoa thường)', 'bằng', 'bằng(phù hợp hoa thường)', 'null', 'not null'],
        filternumericcomparisonoperators: ['bằng', 'không bằng', 'ít hơn', 'ít hơn hoặc bằng', 'lớn hơn', 'lớn hơn hoặc bằng', 'null', 'not null'],
        filterdatecomparisonoperators: ['equal', 'not equal', 'less than', 'less than or equal', 'greater than', 'greater than or equal', 'null', 'not null'],
        filterbooleancomparisonoperators: ['equal', 'not equal'],
        validationstring: "Giá trị đã nhập không hợp lệ",
        emptydatastring: "Không có dữ liệu nào để hiển thị",
        filterselectstring: "Select Filter",
        loadtext: "Đang tải...",
        clearstring: "Làm sạch",
        todaystring: "Hôm nay"
    };
</script>